name: bot-detector
channels:
  - defaults
dependencies:
  - python
  - notebook
  - jupyterlab
  - numpy
  - pandas
  - scipy<1.13
  - scikit-learn
  - nltk
  - gensim
  - tqdm
  - matplotlib
  - pip
  - pip:
    - torch
    - torchvision
    - emoji
    - transformers
    - wordcloud
